### ISSUE TITLE
Crash when click or swap to tab REQUEST # & HEADERS 

### ISSUE THREAD

**Issue by glm-mawla** [jainsahab/AndroidSnooper#24]
When click on 2nd or 3rd tab, it's crashed.
**occurred on most of the android version

**Solution:**
have been solved by changing following:
replace following snippets-
In class _HttpCallActivity_:
> tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
     ....

by 
>     tabLayout.addOnTabSelectedListener(new TabLayout.BaseOnTabSelectedListener() {   ....

**please update this library with resolving this issue**

Thanks

**Comment by jainsahab** [comment]
Hi @glm-mawla, Moth probably You are also facing the problem that we have observed in #23 . Both `TabLayout#setOnTabSelectedListener` and `TabLayout$BaseOnTabSelectedListener` are deprecated. You can see yourself here [here](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/tabs/TabLayout.java).

If you lock in your version dependency to implementation 'com.google.android.material:material:1.0.0', it should work. They've maintained the backward compatibility in this version.

**Comment by glm-mawla** [comment]
Hello @jainsahab , already add dependency implementation 'com.google.android.material:material:1.0.0', but same issue occurred when I using 

> tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {

**Comment by jainsahab** [comment]
HI @glm-mawla . Could you please provide the output for ` ./gradlew androidDependencies`?  Also would you be able to share a dummy project which replicates this issue?

**Comment by jainsahab** [comment]
Hi @glm-mawla closing this issue for now. If you feel issue still persists, feel free to open it again.
Thanks,
