### ISSUE TITLE
Exception with material design version

### ISSUE THREAD

**Issue by retsameht01** [jainsahab/AndroidSnooper#25]
When my using material version 1.1.0-alpha05, the snooper library crashes with the following exception:

 Caused by: java.lang.ClassCastException: com.prateekj.snooper.networksnooper.activity.HttpCallActivity$setupUi$1 cannot be cast to com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener
09-24 11:41:47.662 11526 11526 E AndroidRuntime: 	at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.setupUi(HttpCallActivity.kt:72)
09-24 11:41:47.662 11526 11526 E AndroidRuntime: 	at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.onCreate(HttpCallActivity.kt:61)

Are there plans to update the library using material version 1.1.0 or later? Looks like it's using 1.0.0 which is quite old.

**Comment by dannybduval** [comment]
Yea, the style (`@style/ThemeOverlay.AppCompat.Dark.ActionBar`) is not compatible with `com.google.android.material.tabs.TabLayout`.

Per https://material.io/develop/android/components/tabs#theming-tabs, you'll need to have the parent set appropriately or the enforcement part of the layout will throw this exception.

**Comment by jainsahab** [comment]
@retsameht01 i could reproduce the crash using the material's version you suggested i.e. 1.1.0-alpha05. I've upgraded it to latest version now and working fine and release `1.5.6`.
but if parent project is enforcing the dependency version you are using, it'll fail again for the same reason.

**Comment by jainsahab** [comment]
Version `1.5.6` is available on maven central. Closing this issue for now. Feel free to open it incase we face this issue again.
Thanks,

**Comment by retsameht01** [comment]
Appreciate the update. Thank you
