### ISSUE TITLE
How do I view the request list

### ISSUE THREAD

**Issue by s3hengwu** [jainsahab/AndroidSnooper#31]
How do I view the request list
![2](https://user-images.githubusercontent.com/8500025/130885554-743ab9b8-b236-44d7-a5ac-166196684568.png)

**Comment by jainsahab** [comment]
Hi @s3hengwu , As mentioned you'll have to  shake your device to trigger the shake gesture, which will open the http calls.

We can probably have a permanent notification during the app run which would be another way to access this list, but for now please use the Shake gesture.

**Comment by s3hengwu** [comment]
got it
